### ISSUE TITLE
review author list

### ISSUE THREAD

**Issue by mbjones** [NCEAS/flowers#1]
Review the author list in DESCRIPTION for completeness and accuracy.

**Comment by oharac** [comment]
I think the author list looks good, though I wasn't there for the original plot so can't verify any farther back than Ben Best.

**Comment by Melsteroni** [comment]
Here is my understanding: 
The original aster() (base package) based code was developed by Jim Regetz, Darren Hardy, and Ben Best.  
The updated ggplot2 code was mainly developed by @oharac, @jules32, @melsteroni with inputs from other people along the way (juliette and jamie?).

**Comment by mbjones** [comment]
Thanks for the input.  I added Jamie and Juliette in sha 4dbfa79 so closing this ticket.
